spring:
  application:
    name: reactive-cassandra-service

  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: keyspaceboottech
    local-datacenter: datacenter1
    schema-action: none


# Logging
logging:
  level:
    org.springframework.data.cassandra: DEBUG
    com.datastax.oss.driver: INFO
    reactor.netty: INFO